[package]
name = "error1"
edition = "2021"
publish = false

[dependencies]
anyhow = { version = "1.0.91", features = ["backtrace"] }
thiserror = "1.0.65"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
