[package]
name = "jsonwebtoken1"
edition = "2024"
publish = false

[dependencies]
jsonwebtoken = { version = "10.0.0", features = ["aws_lc_rs"] }
serde = { version = "1.0.228", features = ["derive"] }
