[package]
name = "async-graphql3"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
async-graphql = "7.0.17"
async-trait = "0.1.89"
serde_json = "1.0.143"
tokio = { version = "1.47.1", features = ["full"] }
