[package]
name = "serde-path-to-error1"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde-firestore-value = "0.24.1"
serde_json = "1.0.145"
serde_path_to_error = "0.1.20"
