[package]
name = "jsonwebtoken2"
edition = "2024"
publish = false

[dependencies]
jsonwebtoken = { version = "10.1.0", features = ["rust_crypto"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
