[package]
name = "quick_xml1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-xml = "0.27.1"

[dev-dependencies]
anyhow = "1.0.68"
