[package]
name = "time1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
time = { version = "0.3.9", features = ["formatting", "parsing"] }
