[package]
name = "argon21"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = { version = "0.5.3", features = ["std"] }
base64 = "0.22.1"
rand_core = { version = "0.6", features = ["getrandom"] }
